version: "3.7"

services:
  mysql:
    image: mysql:9.1.0
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: iamninja-mysql
    networks:
      - iamninja
    environment:
      MYSQL_ROOT_PASSWORD: 1!QQQqqq
      MYSQL_DATABASE: iamninja

networks:
  iamninja:

volumes:
  mysql:
